name: Build dump1090-fa

on: [ push, pull_request ]

jobs:
  build:
    name: Build dump1090-fa
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        compiler:
          - gcc-10
          - gcc-12
          - gcc-14
          - clang-20
    runs-on: ${{ matrix.image }}
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install build prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends debhelper librtlsdr-dev libbladerf-dev libhackrf-dev liblimesuite-dev libsoapysdr-dev libusb-1.0-0-dev pkg-config libncurses5-dev ${{ matrix.compiler }}
      - name: Build it
        run: |
          make RTLSDR=yes BLADERF=yes HACKRF=yes LIMESDR=yes SOAPYSDR=yes all
      - name: Run tests
        run: |
          make test
